name: Backend Tests

on:
  push:
    branches: ["**"]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Run tests with coverage
        run: deno test --allow-net --allow-env --env-file=.env --allow-read --allow-run --allow-sys --allow-import --unstable-kv --parallel --coverage=cov/
        working-directory: ./backend

      - name: Generate coverage report
        run: deno coverage --lcov cov/ > cov.lcov
        working-directory: ./backend

      - name: Generate detailed coverage report
        run: deno coverage --lcov --html cov/ --output=cov-html
        working-directory: ./backend

      - name: Check coverage thresholds
        run: |
          # Generate coverage output and extract percentages
          COVERAGE_OUTPUT=$(deno coverage cov/)
          
          # Extract line and branch coverage percentages from the "All files" row
          COVERAGE_LINE=$(echo "$COVERAGE_OUTPUT" | grep -E "All files" | awk '{gsub(/[^0-9.]/, "", $2); gsub(/[^0-9.]/, "", $4); print $2, $4}')
          BRANCH_COVERAGE=$(echo $COVERAGE_LINE | awk '{print $1}')
          LINE_COVERAGE=$(echo $COVERAGE_LINE | awk '{print $2}')
          
          echo "Line coverage: ${LINE_COVERAGE}%"
          echo "Branch coverage: ${BRANCH_COVERAGE}%"
          
          # Check if coverage meets thresholds
          if (( $(echo "$LINE_COVERAGE < 80" | bc -l) )); then
            echo "❌ Line coverage (${LINE_COVERAGE}%) is below the required 80%"
            exit 1
          fi
          
          if (( $(echo "$BRANCH_COVERAGE < 70" | bc -l) )); then
            echo "❌ Branch coverage (${BRANCH_COVERAGE}%) is below the required 70%"
            exit 1
          fi
          
          echo "✅ Coverage thresholds met: Line coverage ${LINE_COVERAGE}%, Branch coverage ${BRANCH_COVERAGE}%"
        working-directory: ./backend

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/cov.lcov
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./backend/cov-html/
          retention-days: 30 